before_install: 
  - sudo dpkg -P libyajl1 || true
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
bundler_args: --without development_extras
script:  rake compile; rake spec
after_success: gem install yajl-ruby; gem install json; gem install psych; FORCE_FFI_YAJL="ext" ffi-yajl-bench
language: ruby
rvm:
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ruby-head
  - ree
  - rbx-2.2
  - jruby-19mode
  - jruby-18mode
  - jruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 2.1.2
      jdk: openjdk6
    - rvm: 2.1.2
      jdk: openjdk7
    - rvm: 2.1.1
      jdk: openjdk6
    - rvm: 2.1.1
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: openjdk6
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: rbx-2.2
      jdk: openjdk6
    - rvm: rbx-2.2
      jdk: openjdk7
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ree
      jdk: openjdk6
    - rvm: ree
      jdk: openjdk7
    - rvm: jruby-18mode
      jdk: openjdk6
    - rvm: jruby-head
      jdk: openjdk6
