before_install: sudo dpkg -P libyajl1 || true
script: rake install ; lib=`gem which ffi_yajl`; dirname=`dirname $lib`; cd $dirname/..; rspec
after_script: find /home/travis -name libyajl.so
language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ruby-head
  - jruby-head
  - jruby-19mode
#  - jruby-18mode
#  - jruby-19mode
#  - rbx-18mode
#  - rbx-19mode
#  - ruby-head
#  - jruby-head
#  - 1.8.7
#  - ree
#jdk:
#  - openjdk7
#  - oraclejdk7
#  - openjdk6
