before_install: sudo dpkg -P libyajl1 || true
script: rake install ; lib=`gem which ffi_yajl`; dirname=`dirname $lib`; cd $dirname/..; rspec
after_script: find /home/travis -name libyajl.so
language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-2.1.1
  - ruby-head
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby-19mode
  - jruby-18mode
# ffi in jruby-head seems busted
#  - jruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: 1.8.7
      jdk: openjdk6
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: rbx-2.1.1
      jdk: openjdk6
    - rvm: rbx-2.1.1
      jdk: openjdk7
    - rvm: rbx-2.1.1
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ree
      jdk: openjdk6
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7
    - rvm: rbx-18mode
      jdk: openjdk6
    - rvm: rbx-18mode
      jdk: openjdk7
    - rvm: rbx-18.mode
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
