version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"

clone_folder: c:\projects\ffi-yajl
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%SystemRoot%\System32;%SystemRoot%;%SystemRoot%\System32\Wbem
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  # compile needs to have the devkit loaded up
  - C:\Ruby21\DevKit\devkitvars.bat
  - echo %PATH%
  - bundle exec rake compile
  - bundle exec rake spec
